[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js Runtime plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Forms configuration
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
