[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js Runtime plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
